package net.alastairwyse.oraclepermissiongeneratorwebserviceapiconsumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-18T17:52:06.633+09:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "OraclePermissionGeneratorWebServiceAPI", 
                  wsdlLocation = "http://localhost:5000/OraclePermissionGeneratorWebServiceAPI?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class OraclePermissionGeneratorWebServiceAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OraclePermissionGeneratorWebServiceAPI");
    public final static QName BasicHttpBindingIOraclePermissionGeneratorWebServiceAPI = new QName("http://tempuri.org/", "BasicHttpBinding_IOraclePermissionGeneratorWebServiceAPI");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:5000/OraclePermissionGeneratorWebServiceAPI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OraclePermissionGeneratorWebServiceAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:5000/OraclePermissionGeneratorWebServiceAPI?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OraclePermissionGeneratorWebServiceAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OraclePermissionGeneratorWebServiceAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OraclePermissionGeneratorWebServiceAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OraclePermissionGeneratorWebServiceAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OraclePermissionGeneratorWebServiceAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OraclePermissionGeneratorWebServiceAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IOraclePermissionGeneratorWebServiceAPI
     */
    @WebEndpoint(name = "BasicHttpBinding_IOraclePermissionGeneratorWebServiceAPI")
    public IOraclePermissionGeneratorWebServiceAPI getBasicHttpBindingIOraclePermissionGeneratorWebServiceAPI() {
        return super.getPort(BasicHttpBindingIOraclePermissionGeneratorWebServiceAPI, IOraclePermissionGeneratorWebServiceAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOraclePermissionGeneratorWebServiceAPI
     */
    @WebEndpoint(name = "BasicHttpBinding_IOraclePermissionGeneratorWebServiceAPI")
    public IOraclePermissionGeneratorWebServiceAPI getBasicHttpBindingIOraclePermissionGeneratorWebServiceAPI(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIOraclePermissionGeneratorWebServiceAPI, IOraclePermissionGeneratorWebServiceAPI.class, features);
    }

}
